### ISSUE TITLE
when run delay,Could not open pipe.

### ISSUE THREAD

**Issue by xeon-ye** [zk2013/windows_remote_lock_unlock_screen#1]
thanks for your contributions! I  hava a question when running the LockingManager,cmd: lockingmanager delay admin 123456,the console shows ""Could not open pipe.".I have built the provider.dll and  imported the reg file . I run the program on windows 10,any advices for me to solve the problem?

**Comment by qingshanjianke** [comment]
建议先阅读该文件 http://www.mycode.net.cn/platform/windows/1945.html
其实问题很简单，对于64位window系统，我们的程序也需要使用x64编译并当道System32文件夹下，这是一个盲点，为后来者戒之。

**Comment by xeon-ye** [comment]
thx
